# 此yml文件是给客户端使用，而resource目录下的application.yml是给自己这个微服务使用
spring:
  profiles:
    active: dev  # 激活开发环境配置
    
---

---

server:
  port: 4001
spring:
  profiles: dev  # 开发环境
  application:
    name: microservice-config-dev  # 微服务名称

---

server:
  port: 4002
spring:
  profiles: prod  # 开发环境
  application:
<<<<<<< HEAD:microservice-config-application.yml
    name: microservice-config-prod  # 微服务名称
=======
    name: microservice-config-prod  # 微服务名称

>>>>>>> 7e34838430bea8dc54e7d52e21a95afb8561f1a4:microservice-config-application.yml
